# Generated by Django 5.2.3 on 2025-06-22 08:36

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sin título', max_length=200)),
                ('artista', models.CharField(blank=True, max_length=100, null=True)),
                ('album', models.CharField(blank=True, max_length=100, null=True)),
                ('ano_lanzamiento', models.IntegerField(blank=True, null=True)),
                ('es_favorita', models.BooleanField(default=False)),
                ('fecha_agregada', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_registro', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioCancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_relacion', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canciones.cancion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones_favoritas', to='canciones.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'cancion')},
            },
        ),
    ]
